ahmadimamfauzan/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('', include('story1.urls')),
    path('', include('courses.urls')),
    path('', include('story6.urls')),
    path('', include('story7.urls')),
]

courses/urls.py
from django.urls import path

from . import views

app_name = 'courses'

urlpatterns = [
    path('courses-list/', views.coursesList, name='courses-list'),
    path('courses-list/<int:id>', views.courseDetail),
    path('delete-courses/<int:id>', views.deleteCourse, name="delete-course"),
    path('add-course', views.addCourse, name='add-course'),
    path('update-course/<int:id>', views.updateCourse, name='update-course')
]

home/urls.py
from django.urls import path

from . import views

app_name = 'home'

urlpatterns = [
    path('', views.index, name='index'),
    path('portfolio/', views.portfolio, name='portfolio'),
    path('experiences/', views.experiences, name='experiences'),
    path('about/', views.about, name='about')
]

story1/urls.py
from django.urls import path

from . import views

app_name = 'story1'

urlpatterns = [
    path('story-1/', views.story1, name='story-1')
]

story6/urls.py
from django.urls import path

from . import views

app_name = 'story6'

urlpatterns = [
    path('register/', views.daftar, name='daftar'),
    path('delete/', views.hapus, name="hapus"),
    path('activity-list/', views.Utama, name='kegiatan_list'),
]

story7/urls.py
from django.urls import path

from . import views

app_name = 'story7'

urlpatterns = [
    path('story7/', views.story7, name='story7'),
]

courses/models.py
from django.db import models

# Create your models here.

class MyCourse(models.Model):
    name = models.CharField(max_length = 100)
    lecture = models.CharField(max_length = 100)
    sks = models.PositiveIntegerField()
    term = models.PositiveIntegerField()
    room = models.CharField(max_length= 100)
    desc = models.CharField(max_length = 500)

    def __str__(self):
        return self.name

herokuapp/models.py
from django.db import models

# Create your models here.

home/models.py
from django.db import models

# Create your models here.

story1/models.py
from django.db import models

# Create your models here.

story6/models.py
from django.db import models

# Create your models here.
class KegiatanSaya(models.Model):
    NamaKegiatan = models.CharField(max_length=500)
    Deskripsi = models.TextField(max_length=500)
    def __str__(self):
        return self.NamaKegiatan
    def __str__(self):
        return self.Deskripsi   

class Participant(models.Model):
    name = models.CharField(max_length = 200)
    kegiatan = models.ForeignKey(KegiatanSaya, on_delete=models.CASCADE)
    def __str__(self):
        return str(self.kegiatan) + " dan " + self.name

story7/models.py
from django.db import models

# Create your models here.

courses/forms.py
from django import forms

from .models import MyCourse

class CourseForm(forms.ModelForm):
    name = forms.CharField()
    lecture = forms.CharField()
    sks = forms.IntegerField()
    term = forms.IntegerField
    room = forms.CharField()
    desc = forms.CharField()

    class Meta:
        model = MyCourse
        fields = '__all__'

story6/forms.py
from django import forms
from .models import *

class KegiatanForm(forms.ModelForm):
    NamaKegiatan = forms.CharField()
    Deskripsi = forms.Textarea()
    class Meta:
        model = KegiatanSaya
        fields = '__all__'

class ParticipantForm(forms.ModelForm):
    class Meta:
        model =  Participant
        fields = '__all__'

courses/views.py
from django.shortcuts import render, redirect
from .models import MyCourse
from .forms import CourseForm

# Create your views here.

def coursesList(request):
    courses = MyCourse.objects.all()
    return render(request, 'courses-list.html', {'courses':courses})

def courseDetail(request, id):
    courses = MyCourse.objects.get(id=id)
    return render(request, 'course-detail.html', {'courses':courses})

def deleteCourse(request, id):
    course = MyCourse.objects.get(id=id)
    if request.method == 'POST':
        course.delete()
        return redirect('/courses-list')
    return render(request, 'delete-course.html', {'course': course})

def addCourse(request):
    form = CourseForm()
    if request.method == 'POST':
        form = CourseForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/courses-list')
    return render(request, 'course-form.html', {'form':form})

def updateCourse(request, id):
    course = MyCourse.objects.get(id=id)
    form = CourseForm(instance=course)
    if request.method == 'POST':
        form = CourseForm(request.POST, instance=course)
        if form.is_valid():
            form.save()
            return redirect('/courses-list')
    return render(request, 'course-form.html', {'form':form})

herokuapp/views.py
from django.shortcuts import render

# Create your views here.

home/views.py
from django.shortcuts import render

# Create your views here.

def index(request):
    return render(request, 'home/index3.html')

def about(request):
    return render(request, 'home/about.html')

def experiences(request):
    return render(request, 'home/experiences.html')

def portfolio(request):
    return render(request, 'home/portfolio.html')

story1/views.py
from django.shortcuts import render

# Create your views here.

def story1(request):
    return render(request, 'index.html')

story6/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import *
from .forms import *

# Create your views here.
def Utama(request):
    kegiatans = KegiatanSaya.objects.all()
    participants = Participant.objects.all()
    keg_par = []
    for kegiatan in kegiatans:
        kegiatan_partic = []
        for participant in participants:
            if (str(participant.kegiatan) == str(kegiatan)):
                kegiatan_partic.append(participant)
        keg_par.append((kegiatan,kegiatan_partic))
    
    context = {
        "hasil_list" : keg_par
    }
    return render(request, 'kegiatan_list.html', context )

def daftar(request):
    id_kegiatan = request.POST.get('id_kegiatan', None)
    name_participant = request.POST.get('name_participant',None)
    nama_kegiatan = request.POST.get('nama_kegiatan', None)
    deskripsi_kegiatan = request.POST.get('deskripsi_kegiatan', None)

    if (id_kegiatan and name_participant) :
        Participant.objects.create(name=name_participant, kegiatan=KegiatanSaya.objects.get(id = id_kegiatan))
    else:
        KegiatanSaya.objects.create(NamaKegiatan=nama_kegiatan, Deskripsi=deskripsi_kegiatan)

    return redirect('/activity-list')

def hapus(request):
    id_participant = request.POST.get('id_participant', None)
    participant = Participant.objects.get(id = id_participant)
    participant.delete()
    # return render(request, 'story6/ListKegiatan.html')
    return redirect('/activity-list')

story7/views.py
from django.shortcuts import render

# Create your views here.
def story7(request):
    return render(request, 'story7.html')

courses/templates/course-detail.html
{% extends 'home/base.html' %}

{% block content %}

<div class="container-fluid bg-pale-orange">
    <div class="container" style="margin-bottom:100px;margin-top:100px;">
        <div class="row">
            <div class="col-md-12 course">
                <h1>{{ courses.name }}</h1>
                <table class="course-table table" style="text-align: left;" >
                    <tbody>
                        <tr>
                            <th scope="row">Lecturer</th>
                            <td>{{ courses.lecture }}</td>
                        </tr>
                        <tr>
                            <th scope="row">SKS Credit</th>
                            <td>{{ courses.sks }}</td>
                        </tr>
                        <tr>
                            <th scope="row">Term</th>
                            <td>{{ courses.term }}</td>
                        </tr>
                        <tr>
                            <th scope="row">Room</th>
                            <td>{{ courses.room }}</td>
                        </tr>
                        <tr>
                            <th scope="row">Description</th>
                            <td>{{ courses.desc }}</td>
                        </tr>
                    </tbody>
                </table>

                <div class="col-md-12 course" style="margin-top:100px;">
                    <a type="button" class="btn btn-back" href="/courses-list"><b>Back</b></a>
                    <a class="btn btn-delete" style="float: right;" href="{% url 'courses:delete-course' courses.id %}">Delete Course</a>
                    <a class="btn btn-update" style="float: right;" href="{% url 'courses:update-course' courses.id %}">Update Course</a>
                </div>

                
            </div>
        </div>
    </div>
</div>

{% endblock %}

courses/templates/course-form.html
{% extends 'home/base.html' %}
{% load static %}

{% block content %}

<div class="container-fluid bg-pale-orange">
    <div class="container" style="margin-bottom:100px;margin-top:100px;">
        <div class="row">
            <div class="col-md-12 course">
                <h1 class="featurette-heading"><b>Add course</b></h1>
                <form method='POST'>
                    {% csrf_token %}
                    {{ form }}
                    <br>
                    <br>
                    <br>
                    <a type="button" class="btn btn-back" href="{% url 'courses:courses-list' %}"><b>Back</b></a>
                    <button type="submit" class="btn btn-delete">Submit</button>
                </form>
                <br>
            </div>
            <div class="col-md-6 course">
                
            </div>
        </div>
    </div>
</div>

{% endblock %}

courses/templates/courses-list.html
{% extends 'home/base.html' %}

{% load static %}

{% block content %}

<div class="container-fluid bg-pale-orange">
    <div class="container" style="margin-bottom:100px;margin-top:100px;">
        <div class="row">
            <div class="col-md-12 banner-info course">
                <h1 style="color: #842139;">My Courses</h1>
                    <div class="courses-list">
                        {% for i in courses %}
                            <a href="{{ i.id }}" class="list-group-item list-group-item-action mute-bg courses-list"><b>{{ i.name }}</b></a>
                        {% endfor %}
                    </div>
                    <br>
                    <br>
                        <a class="btn btn-update" style="margin:0px" href="{% url 'courses:add-course' %}"><b>Add course</b></a>
                    <br>
            </div>
        </div>
    </div>
</div>

{% endblock %}

courses/templates/delete-course.html
{% extends 'home/base.html' %}

{% load static %}

{% block content %}

<div class="container-fluid bg-pale-orange">
    <div class="container" style="margin-bottom:100px;margin-top:100px;">
        <div class="row">
            <div class="col-md-12 course">
                <h1><b>Delete course</b></h2>
                <form action="{% url 'courses:delete-course' course.id %}" method='POST'>
                {% csrf_token %}
                <p>Are you sure you want to delete "{{course}}"?</p>
                <br>
                <a type="button" class="btn btn-back" href="{% url 'courses:courses-list' %}"><b>Cancel</b></a>
                <button type="submit" class="btn btn-delete"><b>Yes</b></button>
                
            </div>
        </div>
    </div>
</div>

{% endblock %}

home/templates/home/about.html
{% extends "home/base.html" %}
{% load static %}
{% block title %}About Imam{%endblock%}
{% block newver%}active{% endblock %}
{% block content %}

<div class="container-fluid bg-pale-orange">
    <div class="container">
        <div class="row">
        
            <div class="col-md-6 about-container centered">
                <img class="img-responsive" class="about-page-img" src="{% static 'img/home/About-txt.svg'%}" alt="about-txt">
                <p class="desc">My name is Ahmad Imam Fauzan. My friends usually call me with Imam. I was born on May 28th 2000.  I’m a college student in Computer Science University of Indonesia (Fasilkom UI) majoring Information System. I do really like design and for me design is such a thing, I really enjoy it that much. I also into UI/UX and still studying about it. My daily lives is standard like another teenagers in general. That is studying and procrastination, watching youtube or netflix, weight-lifting, swimming, etc. I’m kinda a quiet and calm person, but I do really like to discuss about something interesting with other people, such as design, studies, games, weight-lifting, etc. If you want to know about me, we can have a chit-chat through my social media. </p>
            </div>
        
            <div class="col-md-6 imam-about-img centered">
                <img class="img-responsive" src="{% static 'img/home/Imam-white.svg'%}" alt="imam-about">
            </div>
        </div>
    </div>
</div>

{% endblock %}

home/templates/home/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="{% static 'css/style3.css' %}">
    <link rel="stylesheet" href="{% static 'css/sections-home.css' %}">
    <link rel="stylesheet" href="{% static 'css/about.css' %}">
    <link rel="stylesheet" href="{% static 'css/experiences.css' %}">
    <link rel="stylesheet" href="{% static 'css/portfolio.css' %}">
    <link rel="stylesheet" href="{% static 'css/course.css' %}">
    <link rel="stylesheet" href="{% static 'css/story6.css' %}">
    <title>{% block title %}Welcome!{% endblock %}</title>
    <link rel="shortcut icon" type="image/png" href="{% static 'img/home/aifIcon.png' %}" />
</head>

<body>

    <!-- Nav bar -->
    <header>
        <nav class="navbar">
            <div class="container-fluid">
                <div class="container">
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#micon">
            <div class="tombol">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>                      
            </div>
        </button>
                        <div class="aif-logo">
                            <img src="{% static 'img/home/aifLogo.svg'%}" alt="aif">
                        </div>
                    </div>
                    <div class="collapse navbar-collapse" id="micon">
                        <ul class="nav navbar-nav navbar-right">
                            {% block navhome %}
                            <li><a href="/"><span class="glyphicon glyphicon-home"></span></a></li>{% endblock %}
                            <!--
            <li class="dropdown">
                <a class="dropdown-toggle" data-toggle="dropdown" href="#">about
                <span class="caret"></span></a>
                <ul class="dropdown-menu">
                    <li class="{% block newver%}{% endblock %}"><a href="/about">new version</a></li>
                    <li class="{% block oldver%}{% endblock %}"><a href="/story-1">old version</a></li>
                </ul>
            </li> -->
                            <li><a href="/about">about</a></li>
                            <li><a href="/experiences">experiences</a></li>
                            <li><a href="/portfolio">portfolio</a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </nav>
    </header>
    <!-- End of Navbar -->


    <!-- Content each page -->
    {% block content %} {% endblock %}
    <!-- End of content each page -->


    <!-- Contact me section -->
    <footer>
        <div class="container-fluid bg-black">
            <div class="container">
                <div class="row">

                    <div class="col-md-6 tabel-contact">

                        <table>
                            <tbody>

                                <tr>
                                    <td>
                                        <a href="http://instagram.com/aimamf/" target="_blank"><img class="img-responsive" src="{%static 'img/home/Instagram.png'%}" alt="ig"></a>
                                    </td>
                                    <td style="padding-left:40px;">aimamf</td>
                                </tr>

                                <tr>
                                    <td>
                                        <a href="http://linkedin.com/in/aimamf/" target="_blank"><img class="img-responsive" src="{%static 'img/home/Linkedin.png'%}" alt="linkedin"></a>
                                    </td>
                                    <td style="padding-left:40px;">linkedin.com/in/aimamf</td>
                                </tr>

                                <tr>
                                    <td>
                                        <a href="http://gitlab.com/ahmadimamfauzan/" target="_blank"><img class="img-responsive" src="{%static 'img/home/gitlab.png'%}" alt="gitlab"></a>
                                    </td>
                                    <td style="padding-left:40px;">gitlab.com/ahmadimamfauzan</td>
                                </tr>

                                <tr>
                                    <td>
                                        <a href="http://mailto:ifauzan28@gmail.com" target="_blank"><img class="img-responsive" src="{%static 'img/home/Gmail.png'%}" alt="gmail"></a>
                                    </td>
                                    <td style="padding-left:40px;">ifauzan28@gmail.com</td>
                                </tr>

                            </tbody>
                        </table>

                    </div>

                    <div class="col-md-6">
                        <img class="img-responsive contact-me-img" src="{% static 'img/home/Contact-me.svg'%}" alt="contact-me-txt">
                    </div>
                </div>
            </div>
        </div>
    </footer>
    <!-- End of contact me section -->

</html>

home/templates/home/experiences.html
{% extends "home/base.html" %}
{% load static %}
{% block title %}Imam's Experiences{%endblock%}
{% block experiences%}activate{% endblock %}
{% block content %}

<div class="container-fluid bg-pink">
    <div class="records-bg">
    <div class="container">
        <div class="row">

            <div class="col-md-12 exp-container">
                <img class="experiences-txt" src="{% static 'img/home/Experiences-home.svg'%}" alt="aif">
            </div>

            <div class="col-md-12 exps">

                <table class="exp-table">

                    <tr>
                        <td><p class="exp next-item"><b style="color:#11133A">Deputy of Media Bureau</b><br>Badan Eksekutif Mahasiswa<br>Fasilkom UI<p></td>
                        <td><img class="year" src="{% static 'img/home/2020.png'%}" alt="png"><td>
                    </tr>

                    <tr>
                        <td><p class="exp next-item"><b style="color:#11133A">Staff of Startup Academy</b><br>COMPFEST 12<br>Fasilkom UI<p></td>
                    </tr>

                    <tr>
                        <td><p class="exp next-item"><b style="color:#11133A">Staff of Creative</b><br>Pemilihan Raya<br>Fasilkom UI<p></td>
                        <td><img class="year-next" src="{% static 'img/home/2019.png'%}" alt="png"><td>
                    </tr>

                    <tr>
                        <td><p class="exp next-item"><b style="color:#11133A">Volunteer - Savior</b><br>9th Ramadhan Jazz Festival<br>Remaja Islam Cut Meutia, Menteng<p></td>
                    </tr>

                    <tr>
                        <td><p class="exp next-item"><b style="color:#11133A">Staff of Publication and Documentation</b><br>Olimpiade Elektro<br>Jakarta State Polytechnic<p></td>
                    </tr>

                    <tr>
                        <td><p class="exp next-item"><b style="color:#11133A">Secretary</b><br>Majelis Perwakilan Kelas (MPK)<br>39 Senior High School Jakarta<br><p></td>
                        <td><img class="year-next" src="{% static 'img/home/2017.png'%}" alt="png"><td>
                    </tr>

                    <tr>
                        <td><p class="exp next-item"><b style="color:#11133A">Staff of Public Relation & Documentation</b><br>Cijantung Kampus Expo (CIKAMPEX)<br>39 Senior High School Jakarta<p></td>
                    </tr>

                    <tr>
                        <td><p class="exp next-item"><b style="color:#11133A">Staff of Documentation</b><br>GADOGADO 7: REBORN & 8:AETHER<br>39 Senior High School Jakarta<p></td>
                        <td><img class="year-next" src="{% static 'img/home/2016.png'%}" alt="png"><td>
                    </tr>

                </table>

            </div>
            
        </div>
    </div>
    </div>
</div>

{% endblock %}

home/templates/home/index2.html
<!DOCTYPE html>
<html lang="en">

{% load static %}

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/style2.css' %}">
    <link rel="stylesheet" href="{% static 'css/index.css' %}">
    <title>Ahmad Imam Fauzan</title>
</head>

<body>
    <div class="nav-container">
    <header class="main-header container">
        <a href="/" class="aif-logo">
            <img src="{% static 'img/home/aifLogo.svg'%}" alt="aif">
        </a>
        <nav class="main-nav">
            <ul>
                <li><a href='about.html'>about</a></li>
                <li><a href='experiences.html'>experiences</a></li>
                <li><a href='portfolio.html'>portfolio</a></li>
            </ul>
        </nav>
    </header>
    </div>
    
    <section class="home-main-section container">
        <div class="image-wrapper"></div>
            <div class="imam-image"> 
            </div>
        <div class="call-to-action">
            <span class="subtitle">hello, I am</span>
            <h1 class="title" style="letter-spacing: 0.043em;margin-top:11px">A.   I M A M</h1>
            <h1 class="title" style="margin-bottom:31px">F A U Z A N</h1>
            
            <div class="line"></div>

            <a href="about.html" class="button-header">Get to know me</a>
        </div>
        <div class="welcome"></div>
    </section>

    <section class="about-me-index">
        <div class="tulisan-tombol"></div>
            <div class="about-me-textr">
                <p class="filled">About me<p>
                <p class="stroked">About me<p>
                <p class="stroked">About me<p>
            </div>
            <a href="about.html" class="button-about">let's mingle well</a>
        </div>
        <div class="patung-wrapper">
            <div class="patung-img">
                <img src="{% static 'img/home/Patung.png'%}" alt="david">
            </div>
        </div>
    </section>
      
</body>

</html>

home/templates/home/index3.html
{% extends "home/base.html" %}
{% load static %}

{% block navhome %}
{% endblock %}

{% block content %}


<div class="container-fluid bg-blue">
    <div class="container">
        <div class="row">

            <div class="col-md-4 banner-info">
                <p>hello, I am</p>
                <h1 style="letter-spacing: 0.043em;margin-top:11px">A.   I M A M</h1>
                <h1 style="margin-bottom:30px">F A U Z A N</h1>
                <div class="line"></div>

                <a href="/about" class="btn btn-about">Get to know me</a>

            </div>

            <div class="col-md-8 banner-image">
                <img class="img-responsive" src="{% static 'img/home/ImamWelcome.svg'%}" alt="welcome">
            </div>

        </div>
    </div>
</div>

<!-- Experiences section -->

<div class="container-fluid bg-pale-orange">
    <div class="container">
        <div class="row">
        
            <div class="col-md-6 records-img">
                <img class="img-responsive" src="{% static 'img/home/Records.svg'%}" alt="records">
            </div>
        
            <div class="col-md-6 centered">
                <a href="/experiences" class="btn btn-experiences">my records</a>
                <img class="img-responsive experiences-img" src="{% static 'img/home/Experiences-home.svg'%}" alt="experiences-text">
            </div>
        </div>
    </div>
</div>

<!-- Portfolio section -->

<div class="container-fluid bg-red">
    <div class="container">
        <div class="row">
        
            <div class="col-md-6 portfolio-container centered">
                <img class="img-responsive portfolio-img" src="{% static 'img/home/Portfolio-home.svg'%}" alt="portfolio-text">
                <a href="/portfolio" class="btn btn-portfolio">handmade by me</a>
            </div>
        
            <div class="col-md-6 hands-img centered">
                <img class="img-responsive" src="{% static 'img/home/Hands.svg'%}" alt="hands">
            </div>
        </div>
    </div>
</div>
</body>

{% endblock %}

story6/templates/kegiatan_list.html
{% extends 'home/base.html' %}
{% load static %}
{% block content %}


    <div class="container-fluid bg-pale-orange">
          <div class="container konten-act">
            <p style="text-align: left; margin-top: 20px;">
                <button class="btn btn-update btn-add" data-toggle="modal" data-target="#tambahKegiatan" >Add activity</button>
            </p>
                <div class="row">
                    {% for hasil in hasil_list %}
                        <div class="col-md-4">
                            <div class="card mt-3 " style="margin-bottom: 20px;">
                  <div class="card-header bg-info text-white card border-info mb-3">
                        <br>
                        <h1 class="nama-kegiatan">{{hasil.0.NamaKegiatan}}</h1>
                        <br>
                    </div>
                    <div class="card-body">
                        <h1 class="card-title">Description</h1>
                        <p class="deskripsi">{{hasil.0.Deskripsi}}</p>
                        <br>
                        <h1 class="card-title">Participants</b>
                        {% for participant in hasil.1 %}
                            <p class="deskripsi">{{participant.name}}</p>
                        {% endfor %}
                        <br><br>
                        <button class="btn btn-delete" data-toggle="modal" data-target="#tambahParticipant{{ hasil.0.id }}" >Register</button>
                        <br><br>
                    </div>
                </div>
            
                
                
                <!-- modal -->  
                <div class="modal fade" id="tambahParticipant{{hasil.0.id}}" tabindex="-1" aria-labelledby="tambahParticipantTitle" aria-hidden="true">
                    <div class="modal-dialog">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h1 class="modal-title" id="exampleModalLabel">Register the {{ hasil.0.NamaKegiatan }} activity?</h1>
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                            <form action="{% url 'story6:daftar' %}" method="post">
                                <div class="modal-body">
                                    {% csrf_token %}
                                    <input type="hidden" name="id_kegiatan" value="{{hasil.0.id}}">
                                    <label for="name_participant">Name: </label>
                                    <input id="name_participant" name="name_participant" type="text" autofocus>
                                </div>
                                <div class="modal-footer">
                                    <button type="button" class="btn btn-delete" data-dismiss="modal">Cancel</button>
                                    <button type="submit" class="btn btn-update">Register</button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
                        
                        </div>

              
              
                    {% endfor %}



                </div>
              
            </div >
            
            <div class="modal fade" id="tambahKegiatan" tabindex="-1" aria-labelledby="tambahKegiatanTitle" aria-hidden="true">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h1 class="modal-title" id="exampleModalLabel">Register the {{ hasil.0.NamaKegiatan }} activity?</h1>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <form action="{% url 'story6:daftar' %}" method="post">
                            <div class="modal-body">
                                {% csrf_token %}
                                <div class="form-group">
                                    <label for="nama_kegiatan">Name: </label>
                                    <input id="nama_kegiatan" name="nama_kegiatan" type="text" autofocus>
                                </div>
                                <div class="form-group">
                                    <label for="deskripsi_kegiatan">Description: </label>
                                    <input id="deskripsi_kegiatan" name="deskripsi_kegiatan" type="text" autofocus>
                                </div>
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-delete" data-dismiss="modal">Cancel</button>
                                <button type="submit" class="btn btn-update">Add</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
    </div>

{% endblock %} 

story7/templates/story7.html
{% extends 'home/base.html' %} {% load static %} {% block content %}
<p>hello world</p>
{% endblock content %}